### ISSUE TITLE
parseDiscordLine will try to parse attachment url/filename

### ISSUE THREAD

**Issue by Scrxtchy** [creesch/discordIRCd#13]
As it stands, the filenames/urls of a message are susceptible to being parsed from markdown to IRC formatting.
This can return an invalid url being displayed on the IRC client

**Comment by creesch** [comment]
Oh, interesting. I suppose this is with urls that have a bunch of underscores in them?

**Comment by Scrxtchy** [comment]
Pretty much, I'm certain that a filename with the underscores will underscore the entire proceeding url afterwards until the filename is used again at the end of the url
