### ISSUE TITLE
Properly deal with IRC v3 capability negotiation

### ISSUE THREAD

**Issue by vizolini** [creesch/discordIRCd#16]
13:41:32 [192] -!- Welcome to the fake Internet Relay Chat Network user
13:41:32 [192] -!- This server was created specifically for you
13:41:44 [192] -!- AWAY :Do not disturb
13:41:44 [192] -!- AWAY :Do not disturb
13:41:44 [192] -!- AWAY :Do not disturb
13:41:44 [192] -!- AWAY :Do not disturb
13:41:44 [192] -!- AWAY :Do not disturb
13:41:44 [192] -!- AWAY :Do not disturb
13:41:44 [192] -!- AWAY :Do not disturb
13:41:44 [192] -!- AWAY :Do not disturb
13:41:44 [192] -!- AWAY :Do not disturb
13:41:44 [192] -!- AWAY :Do not disturb

http://take.ms/dwvsO

**Comment by creesch** [comment]
I guess irssi doesn't support away-notify for users. 

It now does send those by default, proper spec says that it should only be done when the client specifically says it supports it. So I'll have to build in that bit as well.

**Comment by creesch** [comment]
http://ircv3.net/specs/core/capability-negotiation-3.1.html
