### ISSUE TITLE
Inline links for Attached files

### ISSUE THREAD

**Issue by Scrxtchy** [creesch/discordIRCd#2]
Probably the biggest UX issue is that files that are uploaded from other users into a channel are missing.
Easiest solution would to append these as a URL to the end of the message, or as a new line to send

![](https://tenryuu.blob.core.windows.net/astrid/17-03-19_16-07-08.png)

**Comment by creesch** [comment]
Yup, makes total sense. Implemented just now. 

Looking at the message discord sends I also need to handle mentions in a slightly smarter way.
