### ISSUE TITLE
Can't login into the server

### ISSUE THREAD

**Issue by gigafactory** [creesch/discordIRCd#28]
Followed the instructions and every-time I try to connect to the server I get
Connected. Now logging in. * Disconnected (Remote host closed socket)
Connected. Now logging in.* Disconnected (Connection reset by peer)
or some other variation of this.
Can you clarify that hostname in config.js is the same as the server address (in my case 127.0.0.1)
and username is whatever you want and put into the config under username (does it has to be the same as discord username I guess?)
Also the server id of discord server should be under login method /Pass password correct?
Also is githubToken necessary for this to work? 
Thank you.

**Comment by rctgamer3** [comment]
What client are you using?
The username in the config file is the user you're connecting with to discordIRCd. Doesn't matter what the user is called on Discord.
Server ID should be under whatever option there is to set a password for the irc server.
githubToken isn't necessary because it's only for embedding things like gists afaik.

**Comment by gigafactory** [comment]
After looking at this again with a well rested head I can see that my npm install did not go though successfully.
Errors I am getting
``prebuild-install WARN install EACCES: permission denied, access '/root/.npm'
and
`npm WARN discord.js@11.0.0 requires a peer of erlpack@hammerandchisel/erlpack#master but none was installed.
npm WARN discord.js@11.0.0 requires a peer of node-opus@^0.2.0 but none was installed.
npm WARN discord.js@11.0.0 requires a peer of opusscript@^0.0.1 but none was installed.
npm WARN discord.js@11.0.0 requires a peer of uws@^0.12.0 but none was installed.
`
I have tried searching and installing various solution posted on the web without any success.
Any advice? Thanks.

**Comment by creesch** [comment]
Try using sudo for the npm install. The first error seems to indicate it is trying to combile it and needs root for that. 
The other errors can be ignored as they are for optional packages for discord.js

**Comment by creesch** [comment]
Oh and github token is only needed when you set `handleCode` to true.

**Comment by creesch** [comment]
Since I have not heard from you I am going to assume that the issue is solved.
