### ISSUE TITLE
mIRC 7.47 error

### ISSUE THREAD

**Issue by Spasman** [creesch/discordIRCd#32]
Any chance you'll work on getting this to work with mIRC? Or maybe you could give me a lead and I could try to fix it myself?

mIRC won't connect after verifying the username: http://i.imgur.com/tHTOWhk.png

(pardon the funny usernames)

it'd be rad to get my mirc bot into my discord server.

**Comment by creesch** [comment]
It should work on mirc actually, some people got it to work. I'll look up later what they did.

**Comment by Spasman** [comment]
youd be a life saver man. thanks.

**Comment by Scrxtchy** [comment]
just want to make sure since I'm not
are you putting your chosen guildid into the server password?

**Comment by Spasman** [comment]
I figured it out. With servers that have passwords, I usually join using the -w parameter with the /server command in mIRC. But the script doesn't seem to like it when you put the -w, you only need the password. ex. /server <IP> <port> <password>
