### ISSUE TITLE
a few suggestions

### ISSUE THREAD

**Issue by Chew** [creesch/discordIRCd#33]
Hello! I have some suggestions to help improve the IRCd. I'm just gonna compile them into this list so I don't end up making a ton of issues.

1) Server owners should have the "Owner" IRC role (the ~)
2) If a user has a role that matches a irc role (e.g. their discord role is voiced) they should also get the voiced role.
3) Be able to WHOIS a user, and find their ID, Real Discord name (if nicked), their discriminator, and whatever else.

This is it for now, but I might keep adding to it.

**Comment by creesch** [comment]
Some of those are technically possible, others are not really doable. 

For example unlike irc roles on discord can mean a ton of things so there is no easy way to translate that to op, voiced, etc as I'd have to check all roles against channels and what that means for people. 


Server owner can be arranged I guess. 

Whois is something I looked into but where the irc standard doesn't leave much room to be creative.

**Comment by Chewsterchew** [comment]
Maybe like an example for point 3 whois be
WHOIS Chew
Response:
```Chew#discrim (UserID@whatever)```

**Comment by Scrxtchy** [comment]
And you can't always check which roles are which unless your user has `manage roles` permissions within a guild.
You can get the display name name, but not their permissions. This includes checking for channel operators, as well as being able to send messages

2020 Edit: boy was this wrong, don't take it at face value

**Comment by Chew** [comment]
Splitting this into separate issues.
