### ISSUE TITLE
Incoming DMs are ignored

### ISSUE THREAD

**Issue by ToxicFrog** [creesch/discordIRCd#40]
Logged on to Discord through the website today to find out that a few people had sent me DMs that never showed up on IRC. If logs are helpful, I can get someone to send me a DM while I'm logging.

**Comment by creesch** [comment]
Are you connected to the dedicated DM server?

**Comment by ToxicFrog** [comment]
Nope, I had completely forgotten that that was a thing and wasn't connected to it.
