### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by discordpro** [creesch/discordIRCd#46]
When i  tried to run it i get this
Syntax error
![r](https://user-images.githubusercontent.com/24377875/43234257-0ce09a00-9049-11e8-823c-04ebec9295ee.PNG)

**Comment by discordpro** [comment]
is this meant to be used on ubuntu or something

**Comment by Fusselwurm** [comment]
It's supposed to be run with NodeJS, which is available for Windows too: https://nodejs.org/en/

**Comment by creesch** [comment]
Yeah you can't just run it, you need nodejs for it.
