### ISSUE TITLE
Implement/backport message playback on joining. 

### ISSUE THREAD

**Issue by creesch** [creesch/discordIRCd#47]
@Polynomdivision did the work already, but never did put in a pull request as they did a nice job as far as I am concerned. 

https://github.com/Polynomdivision/discordIRCd/commits/master

This would be optional and the number of lines to be played back configurable.

**Comment by Polynomdivision** [comment]
@creesch Totally forgot that I made that change :sweat_smile: I am not that confident in my JavaScript-Game, but I'd be glad to create a PR

**Comment by creesch** [comment]
Thanks again for the pull request!
