### ISSUE TITLE
Crash; Error: read ECONNRESET

### ISSUE THREAD

**Issue by Scrxtchy** [creesch/discordIRCd#5]
Sometimes the server explodes itself requiring a manual restart
```
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1028:11)
    at TCP.onread (net.js:572:26)
```

Unfortunately, that's all I have, I don't have a proper debugger for anything else

**Comment by creesch** [comment]
I think I just fixed this. I didn't have proper handling of clients disconnecting abruptly.

**Comment by creesch** [comment]
Okay, I have been using it the entire day now and did not encounter it anymore. So I am going to assume it is fixed.
