### ISSUE TITLE
seems incompatible with eggdrop

### ISSUE THREAD

**Issue by crazycatdevs** [creesch/discordIRCd#52]
Hello there...

I tried to use discordIRC with an eggdrop... The eggdrop connects well to the server, but don't see the channel when I add it (`.+chan #test` in party-line).
So, I use `.tcl putserv "join #test"` and I can send messages to the channel, but it's always in **pending status** for the eggdrop, so it can't see anything of the conversation.

It seems like some parts of the IRC protocol wasn't well implemented. My eggdrop is set to be compliant with unrealircd.

**Comment by creesch** [comment]
The implementation follows basic irc protocols and no client so far has had issues with joining channels so no idea why your eggdrop isn't working.

**Comment by wtw95** [comment]
@crazycatdevs did you have any further success with this? I'm sure I'm doing something wrong on my eggdrop side, but I can't even get my eggdrop to see the server.

**Comment by crazycatdevs** [comment]
@wtw95 : I finally connect my eggdrop through my bitlbee server and it works quite well.
